In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import keras_tuner 
import string
import random
import datetime
import matplotlib.pyplot as plt
import shutil                      # for deleting folders with files in them 
import os

In [3]:
from tensorflow.python.client import device_lib
def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]
print(get_available_devices())

['/device:CPU:0']

In [4]:
import sys
print (sys.version)
# 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
import tensorflow as tf
print(tf.__version__)

3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
2.5.0

In [5]:
# tensorflow 2.5 needs cuDNN 8.1	CUDA 11.2

negative sampling: https://ieeexplore.ieee.org/document/9010476

keras code reference: https://keras.io/examples/structured_data/collaborative_filtering_movielens/

https://keras.io/guides/training_with_built_in_methods/

Hyperparameter tuning: I ended up going with https://www.tensorflow.org/tutorials/keras/keras_tuner rather than https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams

in my use case with real data, the model kept recommending the same items to everyone, so I made the model select negative examples with probability the inverse of each item's popularity (so that more rare items are upweighted).

In [3]:
# function which outputs a random alpha-numeric string of specified length:
def random_string(nchar):
    available_characters = string.ascii_lowercase+''.join([str(i) for i in range(10)])
    return ''.join( random.choice(available_characters) for i in range(nchar) )
    
# example use:
random_string(20)

'nrf9cbtpvb411k7xilyk'

In [5]:
# each item belongs to exactly one item group (items are distributed uniformly across the item groups)
# each user will only consume items from exactly one item group
n_unique_users = 1000
n_unique_items = 50
n_item_groups = 6
n_items_per_user = 5

user_IDs = [ 'user_' + str(i) + '_' + random_string(10) for i in range(n_unique_users) ]
item_IDs = [ 'item_' + str(i) + '_' + random_string(10) for i in range(n_unique_items) ]

# assign each item to an item group:
item_group_per_item_ref = {}
for i in range(n_item_groups):
    item_group_per_item_ref[f'item_group_{i+1}'] = []

for item_i in item_IDs:
    item_group = random.choice( list(item_group_per_item_ref.keys()) )
    item_group_per_item_ref[item_group].append( item_i )

# store the simulated item population in a dataframe: 
store_intermediate_itemgroup_dfs = []
for item_group_i in item_group_per_item_ref.keys():
    item_IDs_in_group_i = item_group_per_item_ref[item_group_i]
    n_items_in_group_i = len(item_IDs_in_group_i)
    relative_unscaled_item_probs_group_i = np.random.exponential( scale=1, size=n_items_in_group_i )
    store_intermediate_itemgroup_dfs.append( 
        pd.DataFrame(
            {
                'item_group':[item_group_i] * n_items_in_group_i,
                'item_ID':item_IDs_in_group_i,
                'selection_prob': relative_unscaled_item_probs_group_i / sum(relative_unscaled_item_probs_group_i)
            }
        )
    )
item_ref_df = pd.concat( store_intermediate_itemgroup_dfs, axis=0 )    
    
gendata_list = []
user_counter = 0
for user_i in range(n_unique_users):
    if user_counter%1000==0:
        print(user_counter)
    # give each user [n_items_per_user] items that they did buy (positive examples), and [n_items_per_user] items that they didn't buy (negative examples)
    # choose an item group for this user:
    item_group_this_user = random.choice( list( item_group_per_item_ref.keys() ) )  
    items_bought_by_this_user = np.random.choice( 
                                     # items bought must be from their item group                          
                                    a = item_ref_df.query( f'item_group=="{item_group_this_user}"' )['item_ID'].values ,
                                    size = n_items_per_user,
                                    replace = False,
                                    p = item_ref_df.query( f'item_group=="{item_group_this_user}"' )['selection_prob'].values 
                                ).tolist()
    gendata_list.append(
        pd.DataFrame(
            {
                'user_ID':[user_IDs[user_i]]*n_items_per_user,
                'item_ID':items_bought_by_this_user
            }
        )
    )
    #items_not_bought_by_this_user_df = (
    #    item_ref_df
    #    .copy()
    #    .merge( pd.DataFrame({'item_ID':items_bought_by_this_user,'remove':[1]*len(items_bought_by_this_user)}),
    #            how = 'left',
    #            on = 'item_ID'
    #          )
    #    .query('remove.isnull()', engine='python')
    #)
    #items_not_bought_by_this_user_df['selection_prob'] = items_not_bought_by_this_user_df['selection_prob'] / items_not_bought_by_this_user_df['selection_prob'].sum() 
    #random_negative_examples = np.random.choice(                      
    #                                a = items_not_bought_by_this_user_df['item_ID'].values ,
    #                                size = n_items_per_user,
    #                                replace = False,
    #                                p = items_not_bought_by_this_user_df['selection_prob'].values 
    #                            ).tolist()
    #gendata_list.append(
    #    pd.DataFrame(
    #        {
    #            'user_ID':[user_IDs[user_i]]*n_items_per_user*2,
    #            'item_ID':items_bought_by_this_user + random_negative_examples,
    #            'y':[1]*n_items_per_user + [0]*n_items_per_user 
    #        }
    #    )
    #)
    user_counter += 1

full_dataset = pd.concat(gendata_list, axis=0).reset_index()
print( full_dataset.shape )
full_dataset.head(20)

0
(5000, 3)

    index            user_ID             item_ID
0       0  user_0_hmullvm0wd   item_4_drgnl0tu0t
1       1  user_0_hmullvm0wd  item_25_yp69xqno6k
2       2  user_0_hmullvm0wd  item_28_aiandulwnh
3       3  user_0_hmullvm0wd  item_34_rx6vsir4z1
4       4  user_0_hmullvm0wd  item_12_5pmhj9wqq2
5       0  user_1_ephrclbmkm   item_4_drgnl0tu0t
6       1  user_1_ephrclbmkm  item_25_yp69xqno6k
7       2  user_1_ephrclbmkm  item_34_rx6vsir4z1
8       3  user_1_ephrclbmkm   item_3_0cs61gfkxo
9       4  user_1_ephrclbmkm  item_12_5pmhj9wqq2
10      0  user_2_o4kbob5189  item_11_kilcjhg2ky
11      1  user_2_o4kbob5189  item_24_gjcr720fuv
12      2  user_2_o4kbob5189  item_23_8z49ob4opo
13      3  user_2_o4kbob5189  item_37_3iw39rxexw
14      4  user_2_o4kbob5189  item_27_nwehks5pr1
15      0  user_3_4k6vr5n2rj  item_13_3vljltvtkd
16      1  user_3_4k6vr5n2rj  item_31_8d2jg9pg70
17      2  user_3_4k6vr5n2rj   item_8_5oax2ehqjn
18      3  user_3_4k6vr5n2rj  item_48_soto9djvft
19      4  user_3_4k6vr5n2rj  item_19_3kxcxxe0w4

In [6]:
# look at the distribution of item sales in the data:
item_bought_counts = full_dataset[['user_ID','item_ID']].copy().groupby('item_ID').agg(n_bought=('user_ID','count')).reset_index()
# make the distribution of negative examples match the item distribution in the positive examples:
# (this hopefully stops the recommender from just recommending the same items to everyone)
# previously, tried weighting by inverse popularity, but this didn't solve the problem
item_bought_counts['item_selection_prob'] = item_bought_counts['n_bought']
item_bought_counts['item_selection_prob'] = item_bought_counts['item_selection_prob'] / item_bought_counts['item_selection_prob'].sum()

item_bought_counts

               item_ID  n_bought  item_selection_prob
0    item_0_8rb7spaxzw         7               0.0014
1   item_10_959tj0bgrg       124               0.0248
2   item_11_kilcjhg2ky       161               0.0322
3   item_12_5pmhj9wqq2       150               0.0300
4   item_13_3vljltvtkd       167               0.0334
5   item_14_4j2a1e2ff0        80               0.0160
6   item_15_zc6sp5jgyv       161               0.0322
7   item_16_fij8dj9l4c       113               0.0226
8   item_17_f6bh5kogg1        69               0.0138
9   item_18_wxal8b803h        30               0.0060
10  item_19_3kxcxxe0w4       167               0.0334
11   item_1_ym5mehyf85        49               0.0098
12  item_20_p8n32qzzsh        63               0.0126
13  item_21_551ize56gr        85               0.0170
14  item_22_t39hp4e7kv       151               0.0302
15  item_23_8z49ob4opo        70               0.0140
16  item_24_gjcr720fuv       156               0.0312
17  item_25_yp69xqno6k       164               0.0328
18  item_26_9s3j5pf0s8       137               0.0274
19  item_27_nwehks5pr1        82               0.0164
20  item_28_aiandulwnh       112               0.0224
21  item_29_65l6gnmtzb        40               0.0080
22   item_2_ahskd4i1cm        42               0.0084
23  item_30_6tg2weioy0       134               0.0268
24  item_31_8d2jg9pg70       167               0.0334
25  item_32_e255qdbd1f        98               0.0196
26  item_33_jyrjy7k3l6       119               0.0238
27  item_34_rx6vsir4z1       106               0.0212
28  item_35_qdjiqpxnlm       151               0.0302
29  item_36_b41s16otwt        31               0.0062
30  item_37_3iw39rxexw       153               0.0306
31  item_38_8wlaapms8w        22               0.0044
32  item_39_q733g6qyu4       158               0.0316
33   item_3_0cs61gfkxo        33               0.0066
34  item_40_38q5pssmwx        85               0.0170
35  item_41_gp354q4zmx        81               0.0162
36  item_42_v44pxgf2xn       146               0.0292
37  item_43_y2aj7gndck        58               0.0116
38  item_44_52b6raiyci        58               0.0116
39  item_45_hhs64hue3f       114               0.0228
40  item_46_qrsw7ao4ls         9               0.0018
41  item_47_5y1dc86aes        46               0.0092
42  item_48_soto9djvft       165               0.0330
43  item_49_u3dn6e6of2        19               0.0038
44   item_4_drgnl0tu0t       156               0.0312
45   item_5_0mng958vcf        79               0.0158
46   item_6_hgsjat1fy8       129               0.0258
47   item_7_7t9jjl1o2t        21               0.0042
48   item_8_5oax2ehqjn       165               0.0330
49   item_9_a6sle681o2       117               0.0234

In [7]:
# make a list of unique user_IDs and item_IDs:
user_IDs = full_dataset['user_ID'].drop_duplicates().values
item_IDs = full_dataset['item_ID'].drop_duplicates().values
user_IDs[0:5]
item_IDs[0:5]

array(['item_4_drgnl0tu0t', 'item_25_yp69xqno6k', 'item_28_aiandulwnh',
       'item_34_rx6vsir4z1', 'item_12_5pmhj9wqq2'], dtype=object)

In [8]:
# give each customer as many negative examples (items not bought) as they have positive examples:
full_dataset['y'] = 1    # all actual items bought are positive examples
negative_examples_temp_storage_list = []
counter = 0
for user_i in user_IDs:
    items_bought = full_dataset.query(f'user_ID=="{user_i}"')['item_ID'].values.tolist()
    items_not_bought = (          #[i for i in item_IDs if i not in items_bought]
        item_bought_counts
        .merge( 
                pd.DataFrame( {'item_ID':items_bought,'bought_flag':[1]*len(items_bought)} ),
                how = 'left',
                on = 'item_ID'
        )
        .query('bought_flag.isnull()', engine='python')   
    )
    negative_examples = np.random.choice( 
                            items_not_bought['item_ID'].values, 
                            p = items_not_bought['item_selection_prob'].values / items_not_bought['item_selection_prob'].sum(),
                            size = min( [len(items_bought), len(items_not_bought)] ),
                            replace = False
                        )
    negative_examples_temp_storage_list.append(
        pd.DataFrame( {
            'user_ID':[user_i]*len(negative_examples),
            'item_ID':negative_examples,
            'y':[0]*len(negative_examples)
        }
        )
    )
    # print progress to screen:
    print( f'{round( 100 * counter / len(user_IDs), 2 )}%' )
    counter += 1

# add the negative examples to the original dataset:
full_dataset = full_dataset.append( pd.concat(negative_examples_temp_storage_list, axis=0) )
full_dataset = full_dataset.sort_values(['user_ID','item_ID']).reset_index()[['user_ID','item_ID','y']]

full_dataset.sort_values('user_ID')

0.0%
0.1%
0.2%
0.3%
0.4%
0.5%
0.6%
0.7%
0.8%
0.9%
1.0%
1.1%
1.2%
1.3%
1.4%
1.5%
1.6%
1.7%
1.8%
1.9%
2.0%
2.1%
2.2%
2.3%
2.4%
2.5%
2.6%
2.7%
2.8%
2.9%
3.0%
3.1%
3.2%
3.3%
3.4%
3.5%
3.6%
3.7%
3.8%
3.9%
4.0%
4.1%
4.2%
4.3%
4.4%
4.5%
4.6%
4.7%
4.8%
4.9%
5.0%
5.1%
5.2%
5.3%
5.4%
5.5%
5.6%
5.7%
5.8%
5.9%
6.0%
6.1%
6.2%
6.3%
6.4%
6.5%
6.6%
6.7%
6.8%
6.9%
7.0%
7.1%
7.2%
7.3%
7.4%
7.5%
7.6%
7.7%
7.8%
7.9%
8.0%
8.1%
8.2%
8.3%
8.4%
8.5%
8.6%
8.7%
8.8%
8.9%
9.0%
9.1%
9.2%
9.3%
9.4%
9.5%
9.6%
9.7%
9.8%
9.9%
10.0%
10.1%
10.2%
10.3%
10.4%
10.5%
10.6%
10.7%
10.8%
10.9%
11.0%
11.1%
11.2%
11.3%
11.4%
11.5%
11.6%
11.7%
11.8%
11.9%
12.0%
12.1%
12.2%
12.3%
12.4%
12.5%
12.6%
12.7%
12.8%
12.9%
13.0%
13.1%
13.2%
13.3%
13.4%
13.5%
13.6%
13.7%
13.8%
13.9%
14.0%
14.1%
14.2%
14.3%
14.4%
14.5%
14.6%
14.7%
14.8%
14.9%
15.0%
15.1%
15.2%
15.3%
15.4%
15.5%
15.6%
15.7%
15.8%
15.9%
16.0%
16.1%
16.2%
16.3%
16.4%
16.5%
16.6%
16.7%
16.8%
16.9%
17.0%
17.1%
17.2%
17.3%
17.4%
17.5%
17.6%
17.7%
17.8%
17.9%
18.0%
18.1%
18.2%
18.3%
18.4%
18.5%
18.6%
18.7%
18.8%
18.9%
19.0%
19.1%
19.2%
19.3%
19.4%
19.5%
19.6%
19.7%
19.8%
19.9%
20.0%
20.1%
20.2%
20.3%
20.4%
20.5%
20.6%
20.7%
20.8%
20.9%
21.0%
21.1%
21.2%
21.3%
21.4%
21.5%
21.6%
21.7%
21.8%
21.9%
22.0%
22.1%
22.2%
22.3%
22.4%
22.5%
22.6%
22.7%
22.8%
22.9%
23.0%
23.1%
23.2%
23.3%
23.4%
23.5%
23.6%
23.7%
23.8%
23.9%
24.0%
24.1%
24.2%
24.3%
24.4%
24.5%
24.6%
24.7%
24.8%
24.9%
25.0%
25.1%
25.2%
25.3%
25.4%
25.5%
25.6%
25.7%
25.8%
25.9%
26.0%
26.1%
26.2%
26.3%
26.4%
26.5%
26.6%
26.7%
26.8%
26.9%
27.0%
27.1%
27.2%
27.3%
27.4%
27.5%
27.6%
27.7%
27.8%
27.9%
28.0%
28.1%
28.2%
28.3%
28.4%
28.5%
28.6%
28.7%
28.8%
28.9%
29.0%
29.1%
29.2%
29.3%
29.4%
29.5%
29.6%
29.7%
29.8%
29.9%
30.0%
30.1%
30.2%
30.3%
30.4%
30.5%
30.6%
30.7%
30.8%
30.9%
31.0%
31.1%
31.2%
31.3%
31.4%
31.5%
31.6%
31.7%
31.8%
31.9%
32.0%
32.1%
32.2%
32.3%
32.4%
32.5%
32.6%
32.7%
32.8%
32.9%
33.0%
33.1%
33.2%
33.3%
33.4%
33.5%
33.6%
33.7%
33.8%
33.9%
34.0%
34.1%
34.2%
34.3%
34.4%
34.5%
34.6%
34.7%
34.8%
34.9%
35.0%
35.1%
35.2%
35.3%
35.4%
35.5%
35.6%
35.7%
35.8%
35.9%
36.0%
36.1%
36.2%
36.3%
36.4%
36.5%
36.6%
36.7%
36.8%
36.9%
37.0%
37.1%
37.2%
37.3%
37.4%
37.5%
37.6%
37.7%
37.8%
37.9%
38.0%
38.1%
38.2%
38.3%
38.4%
38.5%
38.6%
38.7%
38.8%
38.9%
39.0%
39.1%
39.2%
39.3%
39.4%
39.5%
39.6%
39.7%
39.8%
39.9%
40.0%
40.1%
40.2%
40.3%
40.4%
40.5%
40.6%
40.7%
40.8%
40.9%
41.0%
41.1%
41.2%
41.3%
41.4%
41.5%
41.6%
41.7%
41.8%
41.9%
42.0%
42.1%
42.2%
42.3%
42.4%
42.5%
42.6%
42.7%
42.8%
42.9%
43.0%
43.1%
43.2%
43.3%
43.4%
43.5%
43.6%
43.7%
43.8%
43.9%
44.0%
44.1%
44.2%
44.3%
44.4%
44.5%
44.6%
44.7%
44.8%
44.9%
45.0%
45.1%
45.2%
45.3%
45.4%
45.5%
45.6%
45.7%
45.8%
45.9%
46.0%
46.1%
46.2%
46.3%
46.4%
46.5%
46.6%
46.7%
46.8%
46.9%
47.0%
47.1%
47.2%
47.3%
47.4%
47.5%
47.6%
47.7%
47.8%
47.9%
48.0%
48.1%
48.2%
48.3%
48.4%
48.5%
48.6%
48.7%
48.8%
48.9%
49.0%
49.1%
49.2%
49.3%
49.4%
49.5%
49.6%
49.7%
49.8%
49.9%
50.0%
50.1%
50.2%
50.3%
50.4%
50.5%
50.6%
50.7%
50.8%
50.9%
51.0%
51.1%
51.2%
51.3%
51.4%
51.5%
51.6%
51.7%
51.8%
51.9%
52.0%
52.1%
52.2%
52.3%
52.4%
52.5%
52.6%
52.7%
52.8%
52.9%
53.0%
53.1%
53.2%
53.3%
53.4%
53.5%
53.6%
53.7%
53.8%
53.9%
54.0%
54.1%
54.2%
54.3%
54.4%
54.5%
54.6%
54.7%
54.8%
54.9%
55.0%
55.1%
55.2%
55.3%
55.4%
55.5%
55.6%
55.7%
55.8%
55.9%
56.0%
56.1%
56.2%
56.3%
56.4%
56.5%
56.6%
56.7%
56.8%
56.9%
57.0%
57.1%
57.2%
57.3%
57.4%
57.5%
57.6%
57.7%
57.8%
57.9%
58.0%
58.1%
58.2%
58.3%
58.4%
58.5%
58.6%
58.7%
58.8%
58.9%
59.0%
59.1%
59.2%
59.3%
59.4%
59.5%
59.6%
59.7%
59.8%
59.9%
60.0%
60.1%
60.2%
60.3%
60.4%
60.5%
60.6%
60.7%
60.8%
60.9%
61.0%
61.1%
61.2%
61.3%
61.4%
61.5%
61.6%
61.7%
61.8%
61.9%
62.0%
62.1%
62.2%
62.3%
62.4%
62.5%
62.6%
62.7%
62.8%
62.9%
63.0%
63.1%
63.2%
63.3%
63.4%
63.5%
63.6%
63.7%
63.8%
63.9%
64.0%
64.1%
64.2%
64.3%
64.4%
64.5%
64.6%
64.7%
64.8%
64.9%
65.0%
65.1%
65.2%
65.3%
65.4%
65.5%
65.6%
65.7%
65.8%
65.9%
66.0%
66.1%
66.2%
66.3%
66.4%
66.5%
66.6%
66.7%
66.8%
66.9%
67.0%
67.1%
67.2%
67.3%
67.4%
67.5%
67.6%
67.7%
67.8%
67.9%
68.0%
68.1%
68.2%
68.3%
68.4%
68.5%
68.6%
68.7%
68.8%
68.9%
69.0%
69.1%
69.2%
69.3%
69.4%
69.5%
69.6%
69.7%
69.8%
69.9%
70.0%
70.1%
70.2%
70.3%
70.4%
70.5%
70.6%
70.7%
70.8%
70.9%
71.0%
71.1%
71.2%
71.3%
71.4%
71.5%
71.6%
71.7%
71.8%
71.9%
72.0%
72.1%
72.2%
72.3%
72.4%
72.5%
72.6%
72.7%
72.8%
72.9%
73.0%
73.1%
73.2%
73.3%
73.4%
73.5%
73.6%
73.7%
73.8%
73.9%
74.0%
74.1%
74.2%
74.3%
74.4%
74.5%
74.6%
74.7%
74.8%
74.9%
75.0%
75.1%
75.2%
75.3%
75.4%
75.5%
75.6%
75.7%
75.8%
75.9%
76.0%
76.1%
76.2%
76.3%
76.4%
76.5%
76.6%
76.7%
76.8%
76.9%
77.0%
77.1%
77.2%
77.3%
77.4%
77.5%
77.6%
77.7%
77.8%
77.9%
78.0%
78.1%
78.2%
78.3%
78.4%
78.5%
78.6%
78.7%
78.8%
78.9%
79.0%
79.1%
79.2%
79.3%
79.4%
79.5%
79.6%
79.7%
79.8%
79.9%
80.0%
80.1%
80.2%
80.3%
80.4%
80.5%
80.6%
80.7%
80.8%
80.9%
81.0%
81.1%
81.2%
81.3%
81.4%
81.5%
81.6%
81.7%
81.8%
81.9%
82.0%
82.1%
82.2%
82.3%
82.4%
82.5%
82.6%
82.7%
82.8%
82.9%
83.0%
83.1%
83.2%
83.3%
83.4%
83.5%
83.6%
83.7%
83.8%
83.9%
84.0%
84.1%
84.2%
84.3%
84.4%
84.5%
84.6%
84.7%
84.8%
84.9%
85.0%
85.1%
85.2%
85.3%
85.4%
85.5%
85.6%
85.7%
85.8%
85.9%
86.0%
86.1%
86.2%
86.3%
86.4%
86.5%
86.6%
86.7%
86.8%
86.9%
87.0%
87.1%
87.2%
87.3%
87.4%
87.5%
87.6%
87.7%
87.8%
87.9%
88.0%
88.1%
88.2%
88.3%
88.4%
88.5%
88.6%
88.7%
88.8%
88.9%
89.0%
89.1%
89.2%
89.3%
89.4%
89.5%
89.6%
89.7%
89.8%
89.9%
90.0%
90.1%
90.2%
90.3%
90.4%
90.5%
90.6%
90.7%
90.8%
90.9%
91.0%
91.1%
91.2%
91.3%
91.4%
91.5%
91.6%
91.7%
91.8%
91.9%
92.0%
92.1%
92.2%
92.3%
92.4%
92.5%
92.6%
92.7%
92.8%
92.9%
93.0%
93.1%
93.2%
93.3%
93.4%
93.5%
93.6%
93.7%
93.8%
93.9%
94.0%
94.1%
94.2%
94.3%
94.4%
94.5%
94.6%
94.7%
94.8%
94.9%
95.0%
95.1%
95.2%
95.3%
95.4%
95.5%
95.6%
95.7%
95.8%
95.9%
96.0%
96.1%
96.2%
96.3%
96.4%
96.5%
96.6%
96.7%
96.8%
96.9%
97.0%
97.1%
97.2%
97.3%
97.4%
97.5%
97.6%
97.7%
97.8%
97.9%
98.0%
98.1%
98.2%
98.3%
98.4%
98.5%
98.6%
98.7%
98.8%
98.9%
99.0%
99.1%
99.2%
99.3%
99.4%
99.5%
99.6%
99.7%
99.8%
99.9%

                user_ID             item_ID  y
0     user_0_hmullvm0wd  item_11_kilcjhg2ky  0
1     user_0_hmullvm0wd  item_12_5pmhj9wqq2  1
2     user_0_hmullvm0wd  item_13_3vljltvtkd  0
3     user_0_hmullvm0wd  item_25_yp69xqno6k  1
4     user_0_hmullvm0wd  item_28_aiandulwnh  1
...                 ...                 ... ..
9994  user_9_4akavncwov  item_33_jyrjy7k3l6  1
9995  user_9_4akavncwov  item_36_b41s16otwt  1
9996  user_9_4akavncwov  item_43_y2aj7gndck  0
9997  user_9_4akavncwov  item_44_52b6raiyci  1
9999  user_9_4akavncwov   item_6_hgsjat1fy8  0

[10000 rows x 3 columns]

In [9]:
positive_examples_population_calc = (
    full_dataset
    .query('y==1')
    [['item_ID']]
    .groupby('item_ID')
    .agg( nRows = ('item_ID','count') )
    .reset_index()
)
negative_examples_population_calc = (
    full_dataset
    .query('y==0')
    [['item_ID']]
    .groupby('item_ID')
    .agg( nRows = ('item_ID','count') )
    .reset_index()
)

#positive_examples_population_calc.merge(
#        
#        how = 'full_outer'
#    )

In [10]:
#full_dataset = pd.read_csv( "C://Users//jbolton//Documents//blogs//collab_filter_logs//full_dataset_temp.csv" )
#user_IDs = full_dataset['user_ID'].drop_duplicates().values
#item_IDs = full_dataset['item_ID'].drop_duplicates().values

In [11]:
# assign integer IDs to the users and items:
# (a one-to-one mapping of the existing user_IDs and item_IDs onto integers)
user2user_encoded = {x: i for i, x in enumerate(user_IDs)}     # mapping from user_ID to integer user ID
userencoded2user = {i: x for i, x in enumerate(user_IDs)}      # mapping from integer user ID to user_ID

item2item_encoded = {x: i for i, x in enumerate(item_IDs)}    # mapping from item_ID to integer item ID
item_encoded2item = {i: x for i, x in enumerate(item_IDs)}    # mapping from integer item ID to item_ID

# add the integer versions of the user and item IDs to the dataset:
full_dataset["int_user_ID"] = full_dataset["user_ID"].map(user2user_encoded)
full_dataset["int_item_ID"] = full_dataset["item_ID"].map(item2item_encoded)

In [16]:
validation_indices = []         # to store which rows of the data are going to go to the validation set 
test_indices = []               # to store which rows of the data are going to go to the test set
counter = 0
for userID_i in user_IDs:
    positive_example_row_indices = full_dataset.index[ (full_dataset['user_ID']==userID_i) & (full_dataset['y']==1) ].tolist()
    negative_example_row_indices = full_dataset.index[ (full_dataset['user_ID']==userID_i) & (full_dataset['y']==0) ].tolist()
    indices_of_2_positive_examples = random.sample(positive_example_row_indices, k=2)
    indices_of_2_negative_examples = random.sample(negative_example_row_indices, k=2)
    validation_indices.append( indices_of_2_positive_examples[0] )
    validation_indices.append( indices_of_2_negative_examples[0] )
    test_indices.append( indices_of_2_positive_examples[1] )
    test_indices.append( indices_of_2_negative_examples[1] )
    # print progress to screen:
    #if round( 100 * counter / len(user_IDs), 2 ) % 5 == 0:
    #    print( round( 100 * counter / len(user_IDs), 2 ) )
    #counter += 1

# train_indices = [ i for i in list(full_dataset.index) if i not in set(validation_indices+test_indices) ]   # this takes too long! 
all_indices_df = pd.DataFrame(
    {
        'myindex':list(full_dataset.index)
    }
)
index_to_remove_df = pd.DataFrame(
    {
        'myindex':list(validation_indices+test_indices),
        'remove':[1]*len( list(validation_indices+test_indices) )
    }
)
train_indices = (
    all_indices_df
    .merge( index_to_remove_df, how='left', on='myindex' )
    .query( 'remove.isnull()', engine='python')
    ['myindex']
    .values
)

training_data = full_dataset.iloc[ train_indices ].copy()
validation_data = full_dataset.iloc[ validation_indices ].copy()
test_data = full_dataset.iloc[ test_indices ].copy()

print( 
f"""
nrows total data: {len(full_dataset)}
nrows training data: {len(training_data)}
nrows validation data: {len(validation_data)}
nrows test data: {len(test_data)}
"""
)

nrows total data: 10000
nrows training data: 6000
nrows validation data: 2000
nrows test data: 2000

In [13]:
# prepare model inputs:
#x = full_sim_dataset[['int_user_ID', 'int_item_ID']].values
#y = full_sim_dataset['y'].values
#x_train, x_val, x_test, y_train, y_val, y_test = (
#    x[train_indices],      # x_train
#    x[validation_indices], # x_val
#    x[test_indices],       # x_test
#    y[train_indices],      # y_train
#    y[validation_indices], # y_val
#    y[test_indices]       # y_test
#)

In [18]:
user_IDs

array(['user_0_hmullvm0wd', 'user_1_ephrclbmkm', 'user_2_o4kbob5189',
       'user_3_4k6vr5n2rj', 'user_4_85xhxof6k1', 'user_5_5ylhcsrznw',
       'user_6_hfpakonuwn', 'user_7_fm9c5e4xfz', 'user_8_94r2g3pemn',
       'user_9_4akavncwov', 'user_10_rpm5k08ubx', 'user_11_i77gta7hyo',
       'user_12_wd76at9fde', 'user_13_1l405bc3a4', 'user_14_yixfnozya0',
       'user_15_7v5hec1095', 'user_16_3bcoz1ggpl', 'user_17_o520s5xrzp',
       'user_18_xykx4kxsya', 'user_19_8twyvpe28u', 'user_20_vssves7udg',
       'user_21_no1g4ujeg9', 'user_22_73lpisqmfa', 'user_23_n86l663ett',
       'user_24_vnofpm81u8', 'user_25_whuv2r2qma', 'user_26_chapfm4h26',
       'user_27_0dr1mgwfu3', 'user_28_porp16wyjm', 'user_29_s5ehn7xlhu',
       'user_30_mikdntk292', 'user_31_plxpf1te89', 'user_32_q3v0jkqbpb',
       'user_33_drr0dlzij2', 'user_34_fiicqpsfj9', 'user_35_rqt17ttvz5',
       'user_36_u1kjtxzzil', 'user_37_incr4g2bcu', 'user_38_xq6bntpyov',
       'user_39_3j8lbh9uqa', 'user_40_nrxw8ibsel', 'user_41_6jkiaq68vh',
       'user_42_g71sxypi0d', 'user_43_2nf9zn32is', 'user_44_agkeo1h4vw',
       'user_45_m1exmpm7dt', 'user_46_zxoii9osh3', 'user_47_pvx85m4ef1',
       'user_48_zrk5j2lhpk', 'user_49_7kgr99xdka', 'user_50_s9dsp3b1ia',
       'user_51_3qkldgcc0w', 'user_52_uqyruqdhcr', 'user_53_r7xec4j3f3',
       'user_54_galgiayrrq', 'user_55_3ry4ib19vu', 'user_56_cwbvbh429b',
       'user_57_8oothbmpmp', 'user_58_8psluk3kjp', 'user_59_u5ewikkzsb',
       'user_60_gzpzlxo2aq', 'user_61_4zlevq91vj', 'user_62_tu3gpkp21o',
       'user_63_z38i0awf1w', 'user_64_xd13tjvddl', 'user_65_67i5brl3xo',
       'user_66_va266l7kpl', 'user_67_2ckpc1jawj', 'user_68_ehoz3m6aia',
       'user_69_mw9ag2wufb', 'user_70_fbpby3xi30', 'user_71_eqh967m2ks',
       'user_72_8d5nrs7dnc', 'user_73_0ib9hjgrhf', 'user_74_wcerrd6044',
       'user_75_rokj0jl8ie', 'user_76_mrs591lr4v', 'user_77_bfd6tn56q9',
       'user_78_30wd7f68r5', 'user_79_z8juaw61hv', 'user_80_x13fbsi0rq',
       'user_81_vnvl21sgpj', 'user_82_zs30s9ekyj', 'user_83_gxjdq28zc2',
       'user_84_scvmieqgob', 'user_85_s8gmso5kpk', 'user_86_o3k5ro4f11',
       'user_87_920qhlmoat', 'user_88_679519eoo9', 'user_89_dk8ovzm2bp',
       'user_90_h08gf3kogo', 'user_91_exo6id57l2', 'user_92_e5q6178br4',
       'user_93_9oe574d629', 'user_94_1822nmaamp', 'user_95_ojegk2eank',
       'user_96_fyffn2z3kt', 'user_97_nyjpk7aktj', 'user_98_j3wy6v68ne',
       'user_99_fv1qe7hw70', 'user_100_h1u2ugtzho', 'user_101_dnp4c2gn1j',
       'user_102_hdk7rle8lg', 'user_103_hu69wmawhr',
       'user_104_7xhc2r4xcg', 'user_105_9japjdfxnq',
       'user_106_f0kpje4dap', 'user_107_mh6kzkfuyz',
       'user_108_r43y0qak1a', 'user_109_5bnlb3jww7',
       'user_110_5cgqkb86np', 'user_111_35ebxbkxjd',
       'user_112_gqihrhxsa3', 'user_113_lfcmy4vq43',
       'user_114_etqvd84uam', 'user_115_zyf8pbwpys',
       'user_116_3x8lg1ud5e', 'user_117_o4m3amiukp',
       'user_118_4qxlorwf03', 'user_119_yv2ay2jrae',
       'user_120_edr7dwyfhl', 'user_121_mc7040p5du',
       'user_122_wv35c749on', 'user_123_6wtq8jr9eq',
       'user_124_tfs4xt7k4n', 'user_125_d6am4i0n3y',
       'user_126_cz19mk9v1o', 'user_127_rs54flm1mx',
       'user_128_54xdrya0fx', 'user_129_aarsm0ut3m',
       'user_130_e8o4ha5kjf', 'user_131_ageuu74igy',
       'user_132_mmlofghazy', 'user_133_13rd1nd17k',
       'user_134_vx07hwhi2y', 'user_135_pm362036tc',
       'user_136_kgdqv87bsh', 'user_137_bwxlcwv0bk',
       'user_138_yrtm5jbmtu', 'user_139_ddsa3m6rdp',
       'user_140_mpepzjj2jf', 'user_141_vjct6qyrcb',
       'user_142_t7lvnzvlqw', 'user_143_6zp3mnbvl6',
       'user_144_9jrrrpsm1p', 'user_145_oswa0s8fl2',
       'user_146_7zesx5mafg', 'user_147_fq9p0511g6',
       'user_148_kesjh3rx7f', 'user_149_q8dfgz9uz4',
       'user_150_xfgfi0txpd', 'user_151_gfo4kp1vz3',
       'user_152_refa5qhe58', 'user_153_5w5tiwdd17',
       'user_154_nglr97pijk', 'user_155_gx3yqva84w',
       'user_156_5sk4dq7bdd', 'user_157_jmhv2ikmha',
       'user_158_wwzcvwc70k', 'user_159_69x1a5vsfa',
       'user_160_5eze8uha5c', 'user_161_dyoprugshn',
       'user_162_02ht2kppz8', 'user_163_lj077hezl4',
       'user_164_mmpwq5tf6f', 'user_165_cpc6f8w6sl',
       'user_166_rkqv227xdb', 'user_167_lx3ml5speo',
       'user_168_7mhl046d3s', 'user_169_l5eq6rojc6',
       'user_170_7o5b290fz9', 'user_171_9e52efdhy2',
       'user_172_zeq3tnbl5g', 'user_173_tpmboz4hrf',
       'user_174_bu6ddv33ur', 'user_175_ej4qrxswru',
       'user_176_2as2qp33tz', 'user_177_nc6mhduhhg',
       'user_178_3m6441gw95', 'user_179_xt3a30dra7',
       'user_180_wozx8e6ja7', 'user_181_jzm3eldjor',
       'user_182_rdm7x5lo0z', 'user_183_ku700lzj0t',
       'user_184_po9nkqdigs', 'user_185_lkp94piin2',
       'user_186_kxwg2pn4xu', 'user_187_x8ut1b7v5p',
       'user_188_t5fkyq8qe8', 'user_189_qjz44nl5fs',
       'user_190_xhhqh4wa6s', 'user_191_yz1iawrbjo',
       'user_192_1f27r0h6ck', 'user_193_fzugkxp6wa',
       'user_194_isug4wg18c', 'user_195_0yygppg531',
       'user_196_gsqu18piry', 'user_197_ic1mxtgxyr',
       'user_198_mjef7d6jap', 'user_199_ms7twweunk',
       'user_200_6sy4ynxsy0', 'user_201_mz8542njpy',
       'user_202_vfgs2asgit', 'user_203_cnjde1pr12',
       'user_204_5zlv02z8uh', 'user_205_1eari3jpib',
       'user_206_hphiw61f92', 'user_207_3xsy1gcvym',
       'user_208_7x3iqw753j', 'user_209_evz0tj1hwz',
       'user_210_z8lfrin7tu', 'user_211_pb1m6c4x9i',
       'user_212_6fp42oolbx', 'user_213_jy3r0q5qd0',
       'user_214_lioctch4o4', 'user_215_8tnszqdci4',
       'user_216_4v5tl11mm3', 'user_217_4gh8lvuqof',
       'user_218_d7jjr0gyi9', 'user_219_vqrs6a6f01',
       'user_220_4sfuilugcq', 'user_221_fwpcfjy8m2',
       'user_222_p4mybvk408', 'user_223_7te6f36kl9',
       'user_224_oz4g1c3rji', 'user_225_eklybxmxeh',
       'user_226_86zh80uulo', 'user_227_lnxnq6qequ',
       'user_228_w0rx36qa9z', 'user_229_d65jdyb6yq',
       'user_230_56m8q6c1ew', 'user_231_150kyg5ai9',
       'user_232_1dwm9uhgh8', 'user_233_4jh9f4jvtk',
       'user_234_ihz1gnnk80', 'user_235_c2z0b0y686',
       'user_236_oyrpqsa24i', 'user_237_8ytyoa1hqf',
       'user_238_o3t69xdipm', 'user_239_25ppw18mtq',
       'user_240_0f430isd87', 'user_241_4928i219kv',
       'user_242_fw21k3lqq4', 'user_243_iyvsyshptp',
       'user_244_7bi6uz1cwz', 'user_245_ck4pbh1j97',
       'user_246_13d8265m0h', 'user_247_1cxf0t49e9',
       'user_248_19cdhg2jcr', 'user_249_op9yhghtbt',
       'user_250_w6la34djr8', 'user_251_2psu2owv3y',
       'user_252_hqvfffmvrz', 'user_253_eo3doli00j',
       'user_254_roiy2yp5by', 'user_255_5ajk8dtbz2',
       'user_256_0g7n7u9iz4', 'user_257_4ybxjaojkw',
       'user_258_wzie59hkjb', 'user_259_skrdpa2ouo',
       'user_260_vk0jtacznc', 'user_261_cd2syaxiii',
       'user_262_gle73gtqjx', 'user_263_40l5g2ero3',
       'user_264_uyrxcn602x', 'user_265_yuy5e74dvr',
       'user_266_3i5xoilxwx', 'user_267_hj6hagglvc',
       'user_268_ppla4w591e', 'user_269_hrwd5hr50w',
       'user_270_77c0ys7i29', 'user_271_451sjsv28a',
       'user_272_6yygambvzl', 'user_273_19n22vmo6b',
       'user_274_kz0q3lsz0p', 'user_275_6sw163zhud',
       'user_276_6fcbh4lb5c', 'user_277_v8yachaws3',
       'user_278_4e4lv0nm9o', 'user_279_3xwbhvz7fu',
       'user_280_m3yzgsf74j', 'user_281_tkp8lfcse3',
       'user_282_org9t0g4b1', 'user_283_fn61dk062w',
       'user_284_e43nugcyu5', 'user_285_rcbndk2v86',
       'user_286_l6vnb4t0ap', 'user_287_etlg5tvkw4',
       'user_288_44ozugqw0c', 'user_289_4vcokher1q',
       'user_290_kkula8cm3w', 'user_291_76r3ipximt',
       'user_292_jkp0wjpj78', 'user_293_n610ke2kbl',
       'user_294_uy9pl02we0', 'user_295_4ed1jdqvhn',
       'user_296_moio3qe59v', 'user_297_ebo2yejb74',
       'user_298_spj18zt0tz', 'user_299_hucioqvxc8',
       'user_300_n29q2ehsd7', 'user_301_y5pryn4t0j',
       'user_302_5j4ius0sip', 'user_303_ie7v9aud06',
       'user_304_93dt6izooo', 'user_305_g0aede05q6',
       'user_306_xyb9i5u3tb', 'user_307_g70mx10a4s',
       'user_308_weg7s72bxy', 'user_309_1zvky11tdu',
       'user_310_jzvpt0mqzf', 'user_311_f5m58q72mg',
       'user_312_h1o3bz5mh6', 'user_313_29dwtqnir1',
       'user_314_iskgfvbk3m', 'user_315_1d0mrl780g',
       'user_316_1ztvr1eyzw', 'user_317_eoylklvhfa',
       'user_318_glxta99d8a', 'user_319_vume59de6r',
       'user_320_2pcfhb0y0f', 'user_321_a7u5io7ees',
       'user_322_0c4knb7qn1', 'user_323_jr3wc50osh',
       'user_324_7psf43imzk', 'user_325_g0bwhalkwv',
       'user_326_bus8ykm9sg', 'user_327_a5m75nqnfv',
       'user_328_we4wvs0940', 'user_329_zbbb1y81h6',
       'user_330_2qzb4063yh', 'user_331_1y543vh59o',
       'user_332_e10jhrznu2', 'user_333_viwtpiuqbv',
       'user_334_1pzl8qdly4', 'user_335_ntw5kxj2e4',
       'user_336_l5qruc1noc', 'user_337_gl6516g29o',
       'user_338_44xs0ad2yj', 'user_339_hcu50tvwt6',
       'user_340_0h9ymc12j5', 'user_341_z4bz826ujw',
       'user_342_478sb9g8ui', 'user_343_a9rdgnog1q',
       'user_344_jwnmtdwabi', 'user_345_5stpfgapu7',
       'user_346_mtsvcv3kgl', 'user_347_46i4cr8vus',
       'user_348_j2k4e2gg5p', 'user_349_m329yp7gq4',
       'user_350_l4kcu8vnid', 'user_351_epzch3j0k9',
       'user_352_rqkucmjy3n', 'user_353_z48jyogs30',
       'user_354_lg0055gz52', 'user_355_7sbv5ii0uw',
       'user_356_f2u961xh22', 'user_357_9ahr72vtzp',
       'user_358_rtapz3qhjb', 'user_359_eli997j1un',
       'user_360_cq8xlmqo9a', 'user_361_tf1dzx2pkp',
       'user_362_vyuy7cv0c7', 'user_363_w6snezrq6f',
       'user_364_6wriebx9tl', 'user_365_twwfdvvlb7',
       'user_366_lun5orkf4p', 'user_367_52lpy4fxph',
       'user_368_ptp5ocm9xg', 'user_369_mv4serzfi7',
       'user_370_o6uv57kjps', 'user_371_sakd63irw6',
       'user_372_uhy8usbt40', 'user_373_emk6td4o2q',
       'user_374_h0r3ghzchf', 'user_375_rbop6vjnxl',
       'user_376_8qino55602', 'user_377_o9ya2p6ykh',
       'user_378_is6qrw1uwk', 'user_379_iq6pnbdw8d',
       'user_380_ge9hqxocrq', 'user_381_n8tsg39mwo',
       'user_382_bepjs2l3df', 'user_383_5gew01ftcb',
       'user_384_701vyxie31', 'user_385_1tge32iu0s',
       'user_386_dtge9v2kk4', 'user_387_7hshqha025',
       'user_388_fxdosqkj13', 'user_389_p9jfe41rad',
       'user_390_2uov5qr00h', 'user_391_iu968fdg90',
       'user_392_vupd98slov', 'user_393_z8ly5tioux',
       'user_394_b4sba6qjm1', 'user_395_brknyr5ih3',
       'user_396_ln63wdv3tr', 'user_397_zsxrruozan',
       'user_398_gsrkiigh1r', 'user_399_aq9gmpk3no',
       'user_400_tvlmu64s0p', 'user_401_otx9jlgq7l',
       'user_402_e5489g77w6', 'user_403_44mj3dz9b2',
       'user_404_81j5hpzjtl', 'user_405_9tf7cfv8mg',
       'user_406_svwrygm595', 'user_407_qla3hmcuol',
       'user_408_kx70z6cnzm', 'user_409_5uaufkq4fz',
       'user_410_vtn0uhczyf', 'user_411_1wgsdzo0j7',
       'user_412_u69r85i99t', 'user_413_qm9pf2z3sv',
       'user_414_44mj96gab7', 'user_415_zdqk3uqw70',
       'user_416_9fcejr6zdy', 'user_417_wbk664jyd8',
       'user_418_ru6qre68zw', 'user_419_wram01dakj',
       'user_420_8xs66f9nt1', 'user_421_lgmztty111',
       'user_422_9ww8mlyrmj', 'user_423_w0xpg70wqa',
       'user_424_m9n5ayvzez', 'user_425_y7olvstcay',
       'user_426_48pgd3bnhi', 'user_427_1wrjnd9nhf',
       'user_428_ov46wkcxzf', 'user_429_ksf3j2qnbe',
       'user_430_33s5wxgo7q', 'user_431_keqbxk9w55',
       'user_432_0womqtfpq9', 'user_433_k0cx2vyzs6',
       'user_434_f2idwk20is', 'user_435_b6buekqhcv',
       'user_436_7y5v5oe3ki', 'user_437_272dngsk3z',
       'user_438_dccv8irvuh', 'user_439_beck5mgdsq',
       'user_440_h8pnu26w1x', 'user_441_9yn7r7zip5',
       'user_442_6lhvkioijr', 'user_443_n0mfnyrpoy',
       'user_444_ktehlhirxe', 'user_445_028pqt1dk0',
       'user_446_hfjk8hqvgr', 'user_447_7blhryc54f',
       'user_448_bagxixctmv', 'user_449_a4ajt2m3y7',
       'user_450_j4v6v6ez6b', 'user_451_pr9sj5681m',
       'user_452_f1gzouc8ka', 'user_453_z98alpr4j9',
       'user_454_55wsrql96j', 'user_455_y6qtk5nbbo',
       'user_456_9jgy7kutkp', 'user_457_q8qpgz86hv',
       'user_458_x3ajqw1owd', 'user_459_nzakzf37w1',
       'user_460_50cwsoit22', 'user_461_0awkhildyl',
       'user_462_6q0b97bzne', 'user_463_c9qo0p5ss9',
       'user_464_0l3moqhcr5', 'user_465_6ckczbfz10',
       'user_466_tj7k4idhs5', 'user_467_3q3d0ah79b',
       'user_468_967jatt5me', 'user_469_6ax3sbmwey',
       'user_470_c7whjy72fm', 'user_471_1mkimr5ben',
       'user_472_xyd3qpb2o1', 'user_473_af44kusvq9',
       'user_474_pr78l6nq8z', 'user_475_oca0cm43vx',
       'user_476_bq2bh7itx9', 'user_477_bpl8nkecb4',
       'user_478_aeomhomsez', 'user_479_827p6rlbia',
       'user_480_eis7t9j20o', 'user_481_9j1nqz8jvz',
       'user_482_esbzo3sice', 'user_483_i2rz9pubrv',
       'user_484_0r2mf4dv5r', 'user_485_c7auve689c',
       'user_486_7h2npjtrut', 'user_487_o04q2nwarl',
       'user_488_6yij5hf9qm', 'user_489_zwmk3dpyr4',
       'user_490_u6h10824t5', 'user_491_s61tw3lfzk',
       'user_492_w5yxs4ynbb', 'user_493_7gusqguapa',
       'user_494_h5a6qb5s32', 'user_495_y1gtxg7s98',
       'user_496_b2h802wsbp', 'user_497_11x2swlf3m',
       'user_498_szgfxjgx7g', 'user_499_0dv2stuzwq',
       'user_500_pqd4s1ksob', 'user_501_1uev8plgsa',
       'user_502_b3uqqzn5be', 'user_503_lepl6wtpi2',
       'user_504_g6wg3ggvhw', 'user_505_ultx402gv7',
       'user_506_d4g1wtury6', 'user_507_jxp9khjiio',
       'user_508_qrhtcm43ph', 'user_509_y4gqll5dii',
       'user_510_1tv5vspgus', 'user_511_h3cb8s43n8',
       'user_512_dn2t7y0oge', 'user_513_p3884hbyuk',
       'user_514_0jx03fygt3', 'user_515_egkggztac1',
       'user_516_2ygy7okl45', 'user_517_spllswz0uo',
       'user_518_qek1q8dzi4', 'user_519_hce7f3nfdq',
       'user_520_aegigjmftn', 'user_521_v5hajtljps',
       'user_522_um7n9ngbdt', 'user_523_hwifeqaapp',
       'user_524_wcahfljgk6', 'user_525_ret9he1ql1',
       'user_526_27tgoq75uf', 'user_527_8vykcwlxkc',
       'user_528_0332tmh828', 'user_529_t9p8ble3qq',
       'user_530_irv0owmo95', 'user_531_55uhusxzf6',
       'user_532_3ebekhf2iv', 'user_533_sgn5ymfo5a',
       'user_534_t5aa5wg1v3', 'user_535_zqxm0ciztp',
       'user_536_575ts1lyhf', 'user_537_zkdz646tcl',
       'user_538_lgxxrusggz', 'user_539_dblgd0wszu',
       'user_540_ll80f2ors7', 'user_541_c2xuvh735t',
       'user_542_r2ymja7fez', 'user_543_u1svl6hs58',
       'user_544_da3lhofe52', 'user_545_l3wgi54r03',
       'user_546_eqc81juzuu', 'user_547_mrmloyk6mt',
       'user_548_e4d0ac4k6i', 'user_549_nh4qbgc4ze',
       'user_550_a738z6ixjp', 'user_551_rnr9lvg9bl',
       'user_552_1e6tc0qx5g', 'user_553_ycpbg6ownv',
       'user_554_rqyt3sm5zv', 'user_555_lmvgz73ov0',
       'user_556_48oklti96a', 'user_557_tuxftux1u9',
       'user_558_k991azo00d', 'user_559_jm0otd6uca',
       'user_560_ixxtjfo2zz', 'user_561_2fa8b4npq4',
       'user_562_4unbt19i4w', 'user_563_vfvk6mr3mk',
       'user_564_ipngb1xhwd', 'user_565_0rdxzf3sh2',
       'user_566_74pw4v3u8k', 'user_567_1b3upjxenw',
       'user_568_3vbl6dwwc8', 'user_569_f1mb0wkxhl',
       'user_570_iwfdhj975l', 'user_571_h6uq681eqt',
       'user_572_nxx844896d', 'user_573_gfdvpimqr0',
       'user_574_tj5drn7dsb', 'user_575_jd6gnnzdcl',
       'user_576_cgejcuxm9n', 'user_577_g3nyrzs1si',
       'user_578_bdivtqtfol', 'user_579_oac5gb8grt',
       'user_580_ft24ujqslp', 'user_581_dwh6trs1ie',
       'user_582_te9ar8h95o', 'user_583_ufsoopicks',
       'user_584_b7e1h482mk', 'user_585_66ychtj166',
       'user_586_9vi4padjjd', 'user_587_ekomjdhvhz',
       'user_588_ej3cnxaqvi', 'user_589_177m27nyj5',
       'user_590_8kuo73b1i3', 'user_591_fp7omewwiz',
       'user_592_8rrm7rnj5o', 'user_593_wi48635xce',
       'user_594_nzlo2v01zi', 'user_595_mo8i1783l7',
       'user_596_08sp7l7ytu', 'user_597_i0e6wc76m6',
       'user_598_hi8944ppfr', 'user_599_oiefryouls',
       'user_600_oyj2c5rwnc', 'user_601_scz0jxqjim',
       'user_602_892n2i4zls', 'user_603_armlwutivk',
       'user_604_osfi7sdzmp', 'user_605_3m138iuc7q',
       'user_606_w3znka8jpe', 'user_607_8uyo0xeexi',
       'user_608_crp8sl60jd', 'user_609_afps6wc6ko',
       'user_610_b8gx43079d', 'user_611_twghue16wh',
       'user_612_5hdet8y810', 'user_613_vjuu12g9z2',
       'user_614_l6yj1if4bf', 'user_615_ctml30v8j8',
       'user_616_wtzgd5wdur', 'user_617_ygd68z6aqu',
       'user_618_g0yg5wnexx', 'user_619_pfc7z4mqxm',
       'user_620_9v8268jd27', 'user_621_3852exc8ya',
       'user_622_v77uoqkzh3', 'user_623_31h7py5jkv',
       'user_624_gbvow3ccoy', 'user_625_q5la3hzvws',
       'user_626_lo1oqhbx4d', 'user_627_8jjjc2cn4t',
       'user_628_9p96rbyn4t', 'user_629_oppy94bbu1',
       'user_630_kidbaclsld', 'user_631_tuupsulqnv',
       'user_632_kvhul768mj', 'user_633_aeondqjsf6',
       'user_634_doia0yjuqw', 'user_635_cdhpepbwjj',
       'user_636_op08cwbmry', 'user_637_en1tazw9hr',
       'user_638_c2jwzxxmhf', 'user_639_7rtwy4h5ek',
       'user_640_gtrp3nj5j6', 'user_641_jrld0gb5sg',
       'user_642_sh7mg5noxx', 'user_643_pdin6e4i8p',
       'user_644_tgjn60ajw2', 'user_645_9gvbm90b3j',
       'user_646_r5y4l209xn', 'user_647_ls0h6pu5vr',
       'user_648_rze964za2h', 'user_649_zg1wcbecb7',
       'user_650_an694hf6dp', 'user_651_qkgnf2r1iy',
       'user_652_t1h70r4lc2', 'user_653_kdmg64u6qx',
       'user_654_nb8mz49cuh', 'user_655_9d2dnhha13',
       'user_656_xf2lt10f3m', 'user_657_jkmc1xeuhw',
       'user_658_on79cnbykz', 'user_659_tpclz5ink7',
       'user_660_f2tmladw0f', 'user_661_4cr1701utw',
       'user_662_hfhjqg2iaq', 'user_663_1f03xlf4d3',
       'user_664_3j8os1eyex', 'user_665_5fw6gm2rya',
       'user_666_vhrjhy0sl6', 'user_667_p19b7ueqxm',
       'user_668_wk47c9ddbs', 'user_669_oeeu0to8al',
       'user_670_j0ieckj861', 'user_671_1rjxq9aq9p',
       'user_672_n9v37ubrxs', 'user_673_9nqs1cf5zg',
       'user_674_btayiva70p', 'user_675_6lhehdjo6u',
       'user_676_d7iqqq10iz', 'user_677_qelakb31c0',
       'user_678_ypuohownof', 'user_679_1udbffxjok',
       'user_680_ngkfx2tnys', 'user_681_sd4vuvpusf',
       'user_682_0p2pt3p2in', 'user_683_usdl0s1yfi',
       'user_684_6ok4ye2has', 'user_685_y5cx5x2sjx',
       'user_686_l7d382jx38', 'user_687_54qremj0dt',
       'user_688_qrlv9uqtlf', 'user_689_maxswxoqo9',
       'user_690_2s4j0c2lcd', 'user_691_nfugi4xk92',
       'user_692_ke0rk0lwfr', 'user_693_ooj4xo96zh',
       'user_694_b9zngxn6jy', 'user_695_ejzx448dkd',
       'user_696_kv21azm20u', 'user_697_px675tmlmb',
       'user_698_98118emj6v', 'user_699_wcosdc2zd4',
       'user_700_hknxhh9rwj', 'user_701_ngidyza0qo',
       'user_702_602enhkliq', 'user_703_yp8i4lnjrp',
       'user_704_ct5piusp4r', 'user_705_t9b3k3res5',
       'user_706_cop19edbxy', 'user_707_hgrovnag7o',
       'user_708_1ieq40xwzd', 'user_709_hppwwphvc7',
       'user_710_liwchkx5vw', 'user_711_s9xhmjmekt',
       'user_712_f0y06cbk8t', 'user_713_got9vx7exf',
       'user_714_03rynwm6in', 'user_715_r57ks3mnc7',
       'user_716_omx0hprhc3', 'user_717_r8x9p413l0',
       'user_718_8ma744okpv', 'user_719_idqn7xo5zr',
       'user_720_oiyn271vdi', 'user_721_vmi1mlm2py',
       'user_722_cnpemf8a54', 'user_723_qiz5dskphh',
       'user_724_lwlxeck2ca', 'user_725_gpnj6bplnr',
       'user_726_5o5ceyxu18', 'user_727_1h8cj3hmq3',
       'user_728_4owr2aji5y', 'user_729_9zy6mqrz4u',
       'user_730_2ujiui37hj', 'user_731_pdw17rpi9k',
       'user_732_efcevbem47', 'user_733_octls5j9h7',
       'user_734_j6v821mez8', 'user_735_uzzv61yih2',
       'user_736_kofaxumpjz', 'user_737_3ypd25aqqt',
       'user_738_yqtm6zeh68', 'user_739_n8d8zpy6bz',
       'user_740_yc3ftxf0sd', 'user_741_75vrwd6ln0',
       'user_742_mialdyk23g', 'user_743_j27rha6f5k',
       'user_744_ak4efmx5oe', 'user_745_c5ffa35l68',
       'user_746_vfrzbp9ghx', 'user_747_r51ew2pi1d',
       'user_748_b5gt8lzd3s', 'user_749_5255nlh7l4',
       'user_750_lpx33r9496', 'user_751_c2b8cr1gi8',
       'user_752_z3uz6cyoli', 'user_753_o53iqezr7j',
       'user_754_7ptlbpf9p2', 'user_755_j8libewtw4',
       'user_756_4a6wi0eveh', 'user_757_za86mzcmdy',
       'user_758_6argpgzgmx', 'user_759_25wa1y9p88',
       'user_760_qqdko8fv1y', 'user_761_ijkpectiw5',

In [17]:
# quick error check: check what has happened with a random user's data:
random_user_ID = random.choice( user_IDs )
print( training_data[['user_ID','int_item_ID','y']].query( f'user_ID=={random_user_ID}') )
print( validation_data[['user_ID','int_item_ID','y']].query( f'user_ID=={random_user_ID}') )
print( test_data[['user_ID','int_item_ID','y']].query( f'user_ID=={random_user_ID}') )
print( full_dataset[['user_ID','int_item_ID','y']].query( f'user_ID=={random_user_ID}') )

UndefinedVariableError: name 'user_230_56m8q6c1ew' is not defined

In [ ]:
# prepare model inputs:
x = full_dataset[['int_user_ID', 'int_item_ID']].values
y = full_dataset['y'].values
x_train, x_val, x_test, y_train, y_val, y_test = (
    x[train_indices],      # x_train
    x[validation_indices], # x_val
    x[test_indices],       # x_test
    y[train_indices],      # y_train
    y[validation_indices], # y_val
    y[test_indices]       # y_test
)

In [ ]:
class RecommenderNet(keras.Model):
    def __init__(self, num_users, num_items, embedding_size, embedding_L2_regularizer, **kwargs):
        super(RecommenderNet, self).__init__(**kwargs)
        self.num_users = num_users
        self.num_items = num_items
        self.embedding_size = embedding_size
        self.user_embedding = layers.Embedding(
            num_users,
            embedding_size,
            embeddings_initializer = "he_normal",
            embeddings_regularizer = keras.regularizers.l2( embedding_L2_regularizer ) # keras.regularizers.l2(1e-6),
        )
        self.user_bias = layers.Embedding(num_users, 1)
        self.item_embedding = layers.Embedding(
            num_items,
            embedding_size,
            embeddings_initializer = "he_normal",
            embeddings_regularizer = keras.regularizers.l2( embedding_L2_regularizer ) # keras.regularizers.l2(1e-6),
        )
        self.item_bias = layers.Embedding(num_items, 1)

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:, 0])
        user_bias = self.user_bias(inputs[:, 0])
        item_vector = self.item_embedding(inputs[:, 1])
        item_bias = self.item_bias(inputs[:, 1])
        dot_user_item = tf.tensordot(user_vector, item_vector, 2)
        # Add all the components (including bias)
        x = dot_user_item + user_bias + item_bias
        # The sigmoid activation forces the rating to between 0 and 1
        return tf.nn.sigmoid(x)

#model = RecommenderNet( 
#    num_users = len(user_IDs), 
#    num_items = len(item_IDs), 
#    embedding_size = EMBEDDING_SIZE 
#)
#model.compile(
#    loss = tf.keras.losses.BinaryCrossentropy(),
#    optimizer = keras.optimizers.Adam(lr=0.001)
#)

def model_builder(hp):
    model = RecommenderNet( 
                num_users = len(user_IDs), 
                num_items = len(item_IDs), 
                embedding_size = hp.Choice( 'embedding_size', values=[5,10,50,100] ),
                embedding_L2_regularizer = hp.Choice('embedding_L2_regularizer', values=[0.0, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1])
    )
    model.compile(
                    loss = tf.keras.losses.BinaryCrossentropy(),
                    optimizer = keras.optimizers.Adam( hp.Choice( 'learning_rate', values=[0.0001, 0.001, 0.01, 0.1] ) )
                )
    return model

In [ ]:
# make my own Keras tuner so that 'batch_size' can also be tuned: 
class MyTuner( keras_tuner.tuners.Hyperband ):
  def run_trial(self, trial, *args, **kwargs):
    # You can add additional HyperParameters for preprocessing and custom training loops
    # via overriding `run_trial`
    kwargs['batch_size'] = trial.hyperparameters.Int('batch_size', 500, 10000, step=500)
    super(MyTuner, self).run_trial(trial, *args, **kwargs)

In [ ]:
# delete current model logs (so that tuning does not continue from previous tuner):
tuner_logs_folder_path = 'C://users//jbolton//Documents//blogs//collab_filter_logs//hyperband_logs//' 
if os.path.isdir( tuner_logs_folder_path ):   # if this folder already exists 
    shutil.rmtree( tuner_logs_folder_path )   # ..then delete it

# define hyperparameter tuner:
tuner = MyTuner(
            model_builder,
            objective = 'val_loss',
            max_epochs = 100,
            factor = 3,
            directory = 'C://users//jbolton//Documents//blogs//collab_filter_logs//hyperband_logs//',
            project_name = 'collab_filter_recommender'
)
#tuner = keras_tuner.Hyperband(
#            model_builder,
#            objective = 'val_loss',
#            max_epochs = 50,
#            factor = 3,
#            directory = 'C://users//jbolton//Documents//blogs//collab_filter_logs//hyperband_logs//',
#            project_name = 'collab_filter_recommender'
#)

In [ ]:
tensorboardLogs_dir = "C://users//jbolton//Documents//blogs//collab_filter_logs//" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard( 
                            log_dir = tensorboardLogs_dir, 
                            histogram_freq = 1
)

early_stopping_monitor = tf.keras.callbacks.EarlyStopping(
    # see https://keras.io/api/callbacks/early_stopping/
    monitor = 'val_loss',  # quantity to monitor
    min_delta = 0,         # an absolute change of less than min_delta, will count as no improvement
    patience = 20,         # Number of epochs with no improvement after which training will be stopped
    verbose = 1,
    mode = 'auto',
    baseline = None,
    restore_best_weights = True # if True, restores the model weights from the epoch with the best value of the monitored quantity
)

tuner.search(
                x = x_train,
                y = y_train,
                epochs = 100,
                verbose = 1,
                validation_data = (x_val, y_val),
                callbacks = [early_stopping_monitor]
)

In [ ]:
# fetch optimal hyperparameters found:
best_hps = tuner.get_best_hyperparameters( num_trials=1 )[0]
print( f"best embedding_size: {best_hps.get('embedding_size')}" )
print( f"best embedding_L2_regularizer: {best_hps.get('embedding_L2_regularizer')}" )
print( f"best learning_rate: {best_hps.get('learning_rate')}" )
print( f"best batch_size: {best_hps.get('batch_size')}" )

# fetch the model with the best hyperparameters found:
model = tuner.hypermodel.build(best_hps)

In [ ]:
train_history = model.fit(
    x = x_train,
    y = y_train,
    batch_size = best_hps.get('batch_size'),
    epochs = 100,
    verbose = 1,
    validation_data = (x_val, y_val),
    callbacks = [early_stopping_monitor],
)

In [ ]:
plt.plot(train_history.history["loss"])
plt.plot(train_history.history["val_loss"])
plt.title("model loss (binary cross entropy)")
plt.ylabel("loss")
plt.xlabel("epoch")
plt.legend(["training set", "validation set"], loc="upper left")
plt.show()

In [ ]:
test_data['predicted_y'] = [ i[0] for i in model.predict(x_test) ]
test_data

In [ ]:
# calculate the proportion of customers for which the correct product had higher predicted_y: 
evaluate_test_set_performance = (
    test_data[['user_ID','y','predicted_y']]
    .pivot_table( 
                    index = 'user_ID',
                    columns = 'y',
                    values = 'predicted_y'
                )
    .reset_index()
)
evaluate_test_set_performance['correct_decision'] = 0
evaluate_test_set_performance.loc[ evaluate_test_set_performance[1]>evaluate_test_set_performance[0] ,'correct_decision'] = 1

print( f"% of customers with correct decision: {100*evaluate_test_set_performance['correct_decision'].sum() / evaluate_test_set_performance.shape[0]}%" )

In [ ]:
# generate top n recommendations for a random customer:
n_items = 10
random_user_ID = random.choice( user_IDs )
items_bought_in_training_data = training_data.loc[ training_data['user_ID']==random_user_ID, 'item_ID'].values.tolist()
# generate a string nicely formatted to show the items that this random customer bought in the training data:
purchase_string = ''
for i in items_bought_in_training_data:
    purchase_string = purchase_string + '\n\t o  ' + i  
all_products_this_customer_for_model_pred = pd.DataFrame(
    {
        'int_user_ID':[ user2user_encoded[random_user_ID] ] * len(item2item_encoded),
        'int_item_ID':item2item_encoded.values()        # all (integer) item_IDs
    }
).values
model_predictions_all_items_this_random_customer = model.predict( all_products_this_customer_for_model_pred )
model_predictions_every_item_this_random_customer_df = pd.DataFrame(
    {
        'user_ID':[random_user_ID] * len(item2item_encoded),
        'item_ID':item2item_encoded.keys(),
        'predicted_y':[ i[0] for i in model_predictions_all_items_this_random_customer ]
    }
).sort_values( 'predicted_y', ascending=False )
recommended_products_string = ''
for i in model_predictions_every_item_this_random_customer_df.head(n_items)['item_ID'].values:
    recommended_products_string = recommended_products_string + '\n\t *  ' + i  
print(
    f"""
    -- customer_ID {random_user_ID} --
    customer bought in training data:
    {purchase_string}
    \ntop {n_items} recommended products to this customer:
    {recommended_products_string}
    """
)